language: java
cache:
  directories:
    - $HOME/.m2
services:
  - xvfb
#before_install:
#  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
#
#install: true

jdk:
  - openjdk12
